### ISSUE TITLE
MakeCode Compatibility

### ISSUE THREAD

**Issue by markdav-is** [tinkertanker/pxt-rotary-encoder-ky040#2]
When I use MakeCode and add this module, my project doesn't seem to put thing in the order the readme intends.  the init code is placed after the events code.  I'm not sure if this is really my problem, but I can't get any events to fire that make sense.
![image](https://user-images.githubusercontent.com/311063/38773505-ed541ec8-4002-11e8-883b-22fc00677836.png)

**Comment by firemansamm** [comment]
Sorry for the late response - I can’t seem to reproduce this. Can you confirm your rotary encoder is wired up correctly?
