### ISSUE TITLE
020 crash in MakeCode v2 and MakeCode beta (06.08.20)

### ISSUE THREAD

**Issue by RRWagner** [tinkertanker/pxt-rotary-encoder-ky040#3]
This program crashes when the encoder is turned rapidly left or right.

https://makecode.microbit.org/_TqjJ4m2pV3Xc

![image](https://user-images.githubusercontent.com/2395551/84086892-c4817700-a99d-11ea-9f09-0479a6dc4e49.png)

**Comment by targetarchitecture** [comment]
I have tried to run this code on my Microbit and get the same error.

**Comment by targetarchitecture** [comment]
@RRWagner I think it's because you're trying to change display the LEDs using the events, if I put the LED parts into the main loop and just have the events set a variable it works.

[https://makecode.microbit.org/_6P6gs49RjeLj](https://makecode.microbit.org/_6P6gs49RjeLj)

**Comment by HyperDuino** [comment]
Yes, that alternate code worked.  Thank you!

But I don't understand why LED control can't be within an event handler.  Is that documented somewhere?  Are there other blocks that can't be inside event handlers?

**Comment by RRWagner** [comment]
Yes, that alternate code worked. Thank you!

But I don't understand why LED control can't be within an event handler. Is that documented somewhere? Are there other blocks that can't be inside event handlers?
